Repository kirk0221/chacha_create1, pull requests merged in 2025-07, with the labels that each got.

#130 ✨ feat: 상품 상세 버튼 연결(및 오류 해결, 코드 스타일 변경)
  src/main/java/com/chacha/create/controller/controller/mainhome/main/HomeMainController.java
  src/main/webapp/WEB-INF/views/main/mypage/mainMyPageCart.jsp
  src/main/webapp/WEB-INF/views/main/mypage/mainMyPageOrderList.jsp
  src/main/webapp/WEB-INF/views/store/productDetail.jsp
  src/main/webapp/WEB-INF/views/store/seller/sellerOrderManage.jsp
  src/main/webapp/resources/css/store/buyer/orderComplete.css
  src/main/webapp/resources/css/store/productDetail.css
  src/main/webapp/resources/css/store/seller/sellerOrderManage.css
Labels: bug, feature, refactor

#146 ✨ feat: 상품 상세 페이지 기능 연동 및 UI 동작 구현
  src/main/java/com/chacha/create/common/dto/product/ProductDetailDTO.java
  src/main/java/com/chacha/create/common/dto/product/ReviewDTO.java
  src/main/java/com/chacha/create/common/mapper/order/OrderMapper.java
  src/main/java/com/chacha/create/controller/rest/buyer/detail/ProductReviewRestController.java
  src/main/java/com/chacha/create/controller/rest/buyer/order/OrderRestController.java
  src/main/java/com/chacha/create/service/store_common/mypage/MyOrderService.java
  src/main/resources/mybatis/mappers/order/orderMapper.xml
  src/main/resources/mybatis/mappers/order/reviewMapper.xml
  src/main/resources/mybatis/mappers/product/productManageMapper.xml
  src/main/resources/mybatis/sqlMapConfig.xml
  src/main/webapp/WEB-INF/views/store/productDetail.jsp
  src/main/webapp/resources/css/store/productDetail.css
  src/main/webapp/resources/js/store/productDetail.js
  src/main/webapp/resources/js/store/productDetailReview.js
Labels: feature

#148 ✨ feat: 스토어 메인페이지 ajax 추가
  src/main/resources/mybatis/mappers/product/mainPageMapper.xml
  src/main/resources/mybatis/mappers/store/storeIdCheck.xml
  src/main/webapp/WEB-INF/views/store/storeMain.jsp
  src/main/webapp/resources/css/store/seller/storeMain.css
  src/main/webapp/resources/js/store/storeMain.js
Labels: feature

#151 ✨ feat: 스토어 구매자 헤더 추가
  src/main/webapp/common/storeMain_nav.jsp
  src/main/webapp/resources/js/store/storeMain_nav.js
Labels: feature

#153 ♻️ refactor: 스토어 구매자 컨트롤러 코드 수정,추가
  src/main/java/com/chacha/create/controller/controller/buyer/main/StoreMainController.java
  src/main/java/com/chacha/create/controller/rest/buyer/main/StoreMainRestController.java
Labels: refactor

#164 ✨ feat: 장바구니 데이터 기능 연동 및 UI 동작 구현
  src/main/java/com/chacha/create/common/dto/member/CartViewDTO.java
  src/main/java/com/chacha/create/controller/rest/store_common/mypage/MyCartRestController.java
  src/main/resources/mybatis/mappers/member/cartMapper.xml
  src/main/webapp/WEB-INF/views/store/buyer/mypage/cart.jsp
  src/main/webapp/resources/css/store/buyer/mypage/cart.css
  src/main/webapp/resources/js/store/productDetail.js
Labels: feature

#168 ✨ feat: 장바구니-결제 데이터 연동
  src/main/java/com/chacha/create/controller/controller/buyer/main/StoreMainController.java
  src/main/webapp/WEB-INF/views/store/buyer/order.jsp
  src/main/webapp/WEB-INF/views/store/buyer/orderComplete.jsp
  src/main/webapp/resources/js/store/buyer/mypage/cart.js
Labels: bug, feature

#173 ✨ feat: 스토어 구매자 전체상품페이지 ajax 연결
  src/main/java/com/chacha/create/controller/rest/buyer/main/StoreMainRestController.java
  src/main/java/com/chacha/create/service/store_common/MainService.java
  src/main/resources/mybatis/mappers/product/mainPageMapper.xml
  src/main/webapp/WEB-INF/views/store/storeAllProducts.jsp
  src/main/webapp/resources/css/store/storeAllProducts.css
  src/main/webapp/resources/js/store/storeAllProduct.js
  src/main/webapp/resources/js/store/store_pagination.js
Labels: feature

#179 ✨ feat: 마이페이지 나의 리뷰 확인
  src/main/java/com/chacha/create/common/dto/product/ReviewDTO.java
  src/main/java/com/chacha/create/common/entity/order/ReviewEntity.java
  src/main/resources/mybatis/mappers/order/reviewMapper.xml
  src/main/webapp/WEB-INF/views/main/mypage/mainMyPageReview.jsp
  src/main/webapp/WEB-INF/views/store/productDetail.jsp
  src/main/webapp/resources/css/main/mypage/mainMyPageReview.css
  src/main/webapp/resources/js/main/mypage/mainMyPageReview.js
Labels: feature

#192 ♻️ refactor: 주문 내역 페이지 통합 및 기능 수정
  src/main/java/com/chacha/create/common/dto/order/OrderListDTO.java
  src/main/java/com/chacha/create/controller/controller/mainhome/mypage/MainMyPageController.java
  src/main/resources/mybatis/mappers/order/orderMapper.xml
  src/main/webapp/WEB-INF/views/main/mypage/mainMyPageOrderList.jsp
  src/main/webapp/WEB-INF/views/store/buyer/mypage/orderList.jsp
  src/main/webapp/resources/css/main/mypage/mainMyPageOrderList.css
  src/main/webapp/resources/css/store/buyer/mypage/orderList.css
  src/main/webapp/resources/js/main/mypage/mainMyPageOrderList.js
Labels: refactor

#193 ✨ feat: 상품 상세 페이지 판매자 신고 모달
  src/main/java/com/chacha/create/controller/rest/buyer/report/ReportModalRestController.java
  src/main/resources/mybatis/mappers/store/storeMapper.xml
  src/main/webapp/WEB-INF/views/store/productDetail.jsp
  src/main/webapp/resources/css/store/productDetail.css
  src/main/webapp/resources/js/store/productDetail.js
  target/classes/mybatis/mappers/order/orderMapper.xml
Labels: feature

#195 🐛 fix: 장바구니 목록 전체가 넘어가는 오류 수정
  src/main/java/com/chacha/create/controller/controller/mainhome/main/HomeMainController.java
  src/main/webapp/WEB-INF/views/main/mypage/mainorder.jsp
  src/main/webapp/WEB-INF/views/store/buyer/order.jsp
  src/main/webapp/resources/css/main/mypage/mainorder.css
  src/main/webapp/resources/css/store/buyer/order.css
  src/main/webapp/resources/js/store/buyer/mypage/cart.js
  src/main/webapp/resources/js/store/buyer/order.js
Labels: bug, refactor

#199 ✨ feat: 상품 상세 페이지 결제하기 버튼 연결
  src/main/java/com/chacha/create/controller/controller/mainhome/main/HomeMainController.java
  src/main/resources/mybatis/mappers/member/cartMapper.xml
  src/main/webapp/WEB-INF/views/store/buyer/orderComplete.jsp
  src/main/webapp/WEB-INF/views/store/productDetail.jsp
  src/main/webapp/resources/js/store/buyer/order.js
  src/main/webapp/resources/js/store/productDetail.js
Labels: feature

#202 ♻️ refactor: 주문 상세 JSP/JS 파일 분리
  src/main/webapp/WEB-INF/views/store/buyer/mypage/orderDetail.jsp
  src/main/webapp/resources/js/store/buyer/mypage/orderDetail.js
Labels: refactor

#209 ✨ feat: 상세 페이지 내 상품 수정 버튼 추가
  src/main/java/com/chacha/create/common/mapper/member/SellerMapper.java
  src/main/java/com/chacha/create/common/mapper/product/ProductMapper.java
  src/main/java/com/chacha/create/controller/rest/seller/product/IsMineController.java
  src/main/java/com/chacha/create/service/seller/product/IsMineService.java
  src/main/resources/mybatis/mappers/member/sellerMapper.xml
  src/main/resources/mybatis/mappers/product/productMapper.xml
  src/main/webapp/WEB-INF/views/store/productDetail.jsp
  src/main/webapp/resources/css/store/productDetail.css
  src/main/webapp/resources/js/store/productDetail.js
Labels: feature

#215 ♻️ refactor: 버튼 연결 경로 수정
  src/main/webapp/WEB-INF/views/main/main.jsp
  src/main/webapp/resources/js/main/mainHome.js
Labels: refactor

#219 ♻️ refactor: 신상품 조회 xml 코드 수정
  src/main/resources/mybatis/mappers/product/mainPageMapper.xml
Labels: refactor

#220 ✨ feat: 자신의 상품에 달린 리뷰 신고 기능 추가
  src/main/java/com/chacha/create/common/entity/store/ReportEntity.java
  src/main/java/com/chacha/create/common/mapper/order/ReviewMapper.java
  src/main/java/com/chacha/create/controller/rest/seller/review/ReviewReportController.java
  src/main/java/com/chacha/create/service/buyer/detail/ReviewService.java
  src/main/java/com/chacha/create/service/buyer/report/ReportModalService.java
  src/main/resources/mybatis/mappers/order/reviewMapper.xml
  src/main/resources/mybatis/mappers/store/reportMapper.xml
  src/main/webapp/WEB-INF/views/store/productDetail.jsp
  src/main/webapp/resources/css/store/productDetail.css
  src/main/webapp/resources/js/store/productDetail.js
  src/main/webapp/resources/js/store/productDetailReview.js
Labels: feature, refactor

#222 🐛 fix: 일부 오류 수정
  src/main/webapp/resources/js/main/mypage/mainMyPage.js
  src/main/webapp/resources/js/store/productDetail.js
Labels: bug

#228 ✨ feat: 로그인 redirect 기능 추가
  src/main/java/com/chacha/create/controller/controller/store_common/AuthController.java
  src/main/java/com/chacha/create/controller/rest/store_common/header/AuthRestController.java
  src/main/webapp/WEB-INF/views/auth/join/joinInfo.jsp
  src/main/webapp/WEB-INF/views/auth/login.jsp
Labels: bug, feature

#232 🐛 fix: 경로 매핑 오류 수정
  src/main/webapp/resources/js/store/productDetail.js
  src/main/webapp/resources/js/store/storeMain.js
Labels: bug

#238 ♻️ refactor: 스토어 판매자 사이드바 공지사항 코드 수정
  src/main/webapp/common/store_seller_sidenav.jsp
Labels: refactor

#241 🐛 fix: 세부 오류 사항 수정
  src/main/resources/mybatis/mappers/order/orderDetailMapper.xml
  src/main/resources/mybatis/mappers/order/orderMapper.xml
  src/main/webapp/WEB-INF/views/main/mypage/mainMyPageReview.jsp
  src/main/webapp/resources/js/main/mypage/mainMyPageOrderList.js
  src/main/webapp/resources/js/main/mypage/mainMyPageReview.js
  src/main/webapp/resources/js/store/buyer/mypage/orderDetail.js
Labels: bug, refactor

#250 🐛 fix: 도메인 배포 시 발생하는 버그 수정
  src/main/java/com/chacha/create/controller/controller/store_common/AuthController.java
  src/main/webapp/resources/js/main/mypage/mainMyPage.js
  src/main/webapp/resources/js/seller/productList.js
  src/main/webapp/resources/js/store/buyer/mypage/cart.js
  src/main/webapp/resources/js/store/productDetail.js
  src/main/webapp/resources/js/store/productDetailReview.js
  src/main/webapp/resources/js/storeAllProduct.js
Labels: bug, refactor

#251 🐛 fix: 로그인/로그아웃 시 경로 중복 문제 수정 2
  src/main/java/com/chacha/create/controller/controller/store_common/AuthController.java
Labels: bug
